name: Build and Deploy Frontend to EC2

on:
  push:
    branches: ["main"]
    paths:
      - "client/**"

env:
  EC2_HOST: 44.222.76.137
  EC2_USER: ubuntu
  DEPLOY_PATH: /website/
  VITE_BACKEND_URL: https://api.sunilspace.me
  VITE_API_URL : https://api.sunilspace.me/api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "SSH OK"
            hostname
            whoami

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install deps & build
        run: |
          cd client
          pnpm install
          echo "VITE_API_URL=${{ env.VITE_API_URL }}" >> .env.production
          echo "VITE_BACKEND_URL=${{ env.VITE_BACKEND_URL }}" >> .env.production
          pnpm run build

      - name: SSH - Clean target dir
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf ${{ env.DEPLOY_PATH }}/*

      - name: Copy dist to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "client/dist/*"
          target: "${{ env.DEPLOY_PATH }}"
